workflows:
  flutter-web-build:
    name: Build Flutter Web
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Flutter Web
        script: |
          flutter build web --release --web-renderer html
    artifacts:
      - build/web/**
