workflows:
  flutter-android:
    name: Build APK
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Clean previous builds
        script: flutter clean
      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
